[[plugins]]
repo = 'Shougo/neocomplete.vim'
on_i = 1

[[plugins]]
repo   = 'Shougo/unite.vim'

[[plugins]]
repo      = 'Shougo/neomru.vim'
on_source = ['unite.vim']

[[plugins]]
repo	  = 'scrooloose/nerdtree'

[[plugins]]
repo	  = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'
